---

# see https://yamllint.readthedocs.io/en/stable/configuration.html#extending-the-default-configuration
extends: default

# see https://yamllint.readthedocs.io/en/stable/configuration.html#ignoring-paths
ignore-from-file:
  - .gitignore
  - .yamlignore

# see https://yamllint.readthedocs.io/en/stable/configuration.html#yaml-files-extensions
yaml-files:
  - '*.yml'

rules:
  # see https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments
  comments:
    ignore: |
      templates/user-data/*.pkrtpl.yml

  # see https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.document_start
  document-start:
    ignore: |
      templates/user-data/*.pkrtpl.yml

  # see https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.line_length
  line-length:
    max: 180

  # see https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.truthy
  truthy:
    allowed-values: [
      'true',
      'false'
    ]

    check-keys: true
