---

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/debug_module.html
- name: debug
  ansible.builtin.debug:
    msg: "included os.yml"
  when:
    - enable_debug_statements is defined
    - enable_debug_statements

# see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
- name: Manage OS Package Operations
  ansible.builtin.include_tasks:
    file: os_packages.yml
  when:
    - os is defined and os.enabled

# see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
- name: Manage OS Directories Operations
  ansible.builtin.include_tasks:
    file: os_directories.yml
  when:
    - os is defined and os.enabled

# see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
- name: Copy `nologin` Message File
  ansible.builtin.template:
    dest: "/etc/nologin"
    src: "nologin.txt"
    mode: "0644"
  when:
    - os.toggles.copy_nologin_file
