---
# see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
- name: Debug
  ansible.builtin.debug:
    msg: included os_packages.yml
  when:
    - enable_debug_statements is defined
    - enable_debug_statements

# see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
- name: Create (generic) Directories
  ansible.builtin.file:
    name: "{{ os.directories.Linux.to_create }}"
    state: directory
    mode: "0644"
  when:
    - ansible_os_family == "Amazon" or ansible_os_family == "Debian" or ansible_os_family == "RedHat"
    - os.toggles.create_directories

# see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
- name: Create (distribution-specific) Directories
  ansible.builtin.file:
    name: "{{ os.directories[ansible_os_family].to_create }}"
    state: directory
    mode: "0644"
  when:
    - ansible_os_family == "Amazon" or ansible_os_family == "Debian" or ansible_os_family == "RedHat"
    - os.toggles.create_directories
    - os.directories is defined and os.directories[ansible_os_family] is defined

# see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
- name: Remove (distribution-specific) Directories
  ansible.builtin.file:
    name: "{{ os.directories[ansible_os_family].to_remove }}"
    state: absent
  when:
    - ansible_os_family == "Amazon" or ansible_os_family == "Debian" or ansible_os_family == "RedHat"
    - os.toggles.remove_directories
    - os.directories is defined and os.directories[ansible_os_family] is defined
