---
# see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
- name: Debug for `{{ plugin_name | upper }}`
  ansible.builtin.debug:
    msg: included tools_nomad_plugins.yml
  when:
    - enable_debug_statements is defined
    - enable_debug_statements

# see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
- name: Create Directory for Nomad Plugins for `{{ plugin_name | upper }}`
  ansible.builtin.file:
    path: "{{ destination }}"
    state: directory
    mode: "0644"
  when:
    - destination is defined

# see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
- name: Set Ansible Facts for HashiCorp-maintained Plugin Binary for `{{ repo_name | upper }}`
  ansible.builtin.set_fact:
    plugin_url: "{{ hashicorp_base_url }}/{{ plugin_name }}/{{ plugin_config.version }}/{{ plugin_name }}_{{ plugin_config.version }}"
  when:
    - plugin_config is defined
    - plugin_config.official is true

# see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
- name: Get HashiCorp-maintained Plugin Binary for `{{ plugin_name | upper }}`
  ansible.builtin.get_url:
    checksum: sha256:{{ plugin_url }}_SHA256SUMS
    dest: "{{ destination }}/"
    mode: "0644"
    url: "{{ plugin_url }}_linux_{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}.zip"
  when:
    - destination is defined
    - plugin_url is defined
    - plugin_config.official is true

# see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
- name: Get community-maintained Plugin Binary for `{{ plugin_name | upper }}`
  ansible.builtin.get_url:
    dest: "{{ destination }}/"
    mode: "0644"
    url: "{{ plugin_config.url }}"
  when:
    - plugin_config is defined
    - plugin_config.url is defined
