---

# This is a Packer-generated file; manual changes will be overwritten.
# see https://github.com/workloads/packer-templates/blob/main/packer/templates/configuration.pkrtpl.yml

# Generated on ${timestamp}

${configuration}
